server:
  port: 8080
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mtb
    username: kaizen
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 60000
      connection-test-query: SELECT 1
      pool-name: booking-service-hikari-cp
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-secret: secret
            scope:
              - openid
              - profile
              - email
              - read
              - write
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: oidc-client
        provider:
          oidc-client:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            issuer-uri: http://localhost:9000
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  data:
    redis:
      host: localhost
      port: 6379

